package vortex.demo.smartu;


/**
* vortex/demo/smartu/AnalyticsConfig.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:18 PM CET
*/

/**
* Updated by idl2j
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:19 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "AnalyticsConfig",
    keys = {"utility"}
)
public final class AnalyticsConfig implements org.omg.CORBA.portable.IDLEntity
{
  public vortex.demo.smartu.UtilityKind utility = null;
  public short timeWindow = (short)0;

  public AnalyticsConfig ()
  {
  } // ctor

  public AnalyticsConfig (vortex.demo.smartu.UtilityKind _utility, short _timeWindow)
  {
    utility = _utility;
    timeWindow = _timeWindow;
  } // ctor

} // class AnalyticsConfig
