package vortex.demo.smartu;


/**
* vortex/demo/smartu/AnalyticsConfigHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:18 PM CET
*/

abstract public class AnalyticsConfigHelper
{
  private static String  _id = "IDL:vortex/demo/smartu/AnalyticsConfig:1.0";

  public static void insert (org.omg.CORBA.Any a, vortex.demo.smartu.AnalyticsConfig that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static vortex.demo.smartu.AnalyticsConfig extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = vortex.demo.smartu.UtilityKindHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "utility",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "timeWindow",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (vortex.demo.smartu.AnalyticsConfigHelper.id (), "AnalyticsConfig", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static vortex.demo.smartu.AnalyticsConfig read (org.omg.CORBA.portable.InputStream istream)
  {
    vortex.demo.smartu.AnalyticsConfig value = new vortex.demo.smartu.AnalyticsConfig ();
    value.utility = vortex.demo.smartu.UtilityKindHelper.read (istream);
    value.timeWindow = istream.read_short ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, vortex.demo.smartu.AnalyticsConfig value)
  {
    vortex.demo.smartu.UtilityKindHelper.write (ostream, value.utility);
    ostream.write_short (value.timeWindow);
  }

}
