package vortex.demo.smartu;


/**
* vortex/demo/smartu/Index.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:18 PM CET
*/

public final class Index implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public float value = (float)0;

  public Index ()
  {
  } // ctor

  public Index (String _key, float _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class Index
