package vortex.demo.smartu;


/**
* vortex/demo/smartu/Meter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:18 PM CET
*/

/**
* Updated by idl2j
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:19 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "Meter",
    keys = {"sn"}
)
public final class Meter implements org.omg.CORBA.portable.IDLEntity
{
  public String sn = null;
  public vortex.demo.smartu.UtilityKind utility = null;
  public float reading = (float)0;
  public float error = (float)0;

  public Meter ()
  {
  } // ctor

  public Meter (String _sn, vortex.demo.smartu.UtilityKind _utility, float _reading, float _error)
  {
    sn = _sn;
    utility = _utility;
    reading = _reading;
    error = _error;
  } // ctor

} // class Meter
