package vortex.demo.smartu;


/**
* vortex/demo/smartu/MeterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:18 PM CET
*/

abstract public class MeterHelper
{
  private static String  _id = "IDL:vortex/demo/smartu/Meter:1.0";

  public static void insert (org.omg.CORBA.Any a, vortex.demo.smartu.Meter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static vortex.demo.smartu.Meter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "sn",
            _tcOf_members0,
            null);
          _tcOf_members0 = vortex.demo.smartu.UtilityKindHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "utility",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "reading",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[3] = new org.omg.CORBA.StructMember (
            "error",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (vortex.demo.smartu.MeterHelper.id (), "Meter", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static vortex.demo.smartu.Meter read (org.omg.CORBA.portable.InputStream istream)
  {
    vortex.demo.smartu.Meter value = new vortex.demo.smartu.Meter ();
    value.sn = istream.read_string ();
    value.utility = vortex.demo.smartu.UtilityKindHelper.read (istream);
    value.reading = istream.read_float ();
    value.error = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, vortex.demo.smartu.Meter value)
  {
    ostream.write_string (value.sn);
    vortex.demo.smartu.UtilityKindHelper.write (ostream, value.utility);
    ostream.write_float (value.reading);
    ostream.write_float (value.error);
  }

}
