package vortex.demo.smartu;


/**
* vortex/demo/smartu/UtilityAnalytics.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:18 PM CET
*/

/**
* Updated by idl2j
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:19 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "UtilityAnalytics",
    keys = {"scope"}
)
public final class UtilityAnalytics implements org.omg.CORBA.portable.IDLEntity
{
  public String scope = null;
  public vortex.demo.smartu.UtilityKind utility = null;
  public vortex.demo.smartu.Index indexes[] = null;

  public UtilityAnalytics ()
  {
  } // ctor

  public UtilityAnalytics (String _scope, vortex.demo.smartu.UtilityKind _utility, vortex.demo.smartu.Index[] _indexes)
  {
    scope = _scope;
    utility = _utility;
    indexes = _indexes;
  } // ctor

} // class UtilityAnalytics
