package vortex.demo.smartu;


/**
* vortex/demo/smartu/UtilityKindHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:18 PM CET
*/

abstract public class UtilityKindHelper
{
  private static String  _id = "IDL:vortex/demo/smartu/UtilityKind:1.0";

  public static void insert (org.omg.CORBA.Any a, vortex.demo.smartu.UtilityKind that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static vortex.demo.smartu.UtilityKind extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (vortex.demo.smartu.UtilityKindHelper.id (), "UtilityKind", new String[] { "ELECTRICITY", "GAS", "WATER"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static vortex.demo.smartu.UtilityKind read (org.omg.CORBA.portable.InputStream istream)
  {
    return vortex.demo.smartu.UtilityKind.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, vortex.demo.smartu.UtilityKind value)
  {
    ostream.write_long (value.value ());
  }

}
