package vortex.demo.smartu;


/**
* vortex/demo/smartu/UtilityKind.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/smartu.idl
* Tuesday, November 4, 2014 9:49:18 PM CET
*/

public class UtilityKind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static vortex.demo.smartu.UtilityKind[] __array = new vortex.demo.smartu.UtilityKind [__size];

  public static final int _ELECTRICITY = 0;
  public static final vortex.demo.smartu.UtilityKind ELECTRICITY = new vortex.demo.smartu.UtilityKind(_ELECTRICITY);
  public static final int _GAS = 1;
  public static final vortex.demo.smartu.UtilityKind GAS = new vortex.demo.smartu.UtilityKind(_GAS);
  public static final int _WATER = 2;
  public static final vortex.demo.smartu.UtilityKind WATER = new vortex.demo.smartu.UtilityKind(_WATER);

  public int value ()
  {
    return __value;
  }

  public static vortex.demo.smartu.UtilityKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected UtilityKind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class UtilityKind
